name: meta-taskwave-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - ipykernel
  - notebook
  - jupyterlab
